package filekoller;

import java.awt.event.*;

public class WindowGui extends javax.swing.JFrame {

    /**
     * Creates new form StarterGUI
     */
    public WindowGui() {
        initComponents();
        starter = new Window(this);
        register();
    }

    private void register()
    {
        goButton.addActionListener( new ActionListener()
        {
            public void actionPerformed( ActionEvent ae )
            {
                starter.openPath( pathComboBox.getSelectedItem().toString() );
            }
        });

        testButton.addActionListener( new ActionListener()
        {
            public void actionPerformed( ActionEvent ae )
            {
                starter.printTestMessage();
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowGui().setVisible(true);
            }
        });
    }

    private Window starter;

   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pathComboBox = new javax.swing.JComboBox<>();
        goButton = new javax.swing.JButton();
        testButton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        editMenu = new javax.swing.JMenu();
        viewMenu = new javax.swing.JMenu();
        ToolsMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pathComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "My Computer", "C:\\", "C:\\Users\\Chrille", "My Documents", "Downloads", " " }));

            goButton.setText("Go");

            testButton.setText("Ts");

            jSplitPane1.setDividerLocation(200);
            jSplitPane1.setDividerSize(4);
            jSplitPane1.setContinuousLayout(true);
            jSplitPane1.setName(""); // NOI18N

            fileMenu.setText("File");
            fileMenu.setToolTipText("File system operations");
            fileMenu.setActionCommand("&File");
            menuBar.add(fileMenu);

            editMenu.setText("Edit");
            editMenu.setToolTipText("Editing of objects and metadata");
            menuBar.add(editMenu);

            viewMenu.setText("View");
            viewMenu.setToolTipText("Visual options");
            menuBar.add(viewMenu);

            ToolsMenu.setText("Tools");
            ToolsMenu.setToolTipText("Advanced tools");
            menuBar.add(ToolsMenu);

            setJMenuBar(menuBar);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pathComboBox, 0, 430, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(testButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSplitPane1)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pathComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(goButton)
                        .addComponent(testButton))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ToolsMenu;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton goButton;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JComboBox<String> pathComboBox;
    private javax.swing.JButton testButton;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables
}
